apiVersion: v2
name: discord-channel
description: Helm chart for provisioning a DiscordChannel CR
type: application
version: 0.3.0
maintainers:
  - name: shopp-ops
    email: danilo.cvijetic10@gmail.com
