apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wallets.apps.shop-operator.io
  annotations:
    shop-operator.io/mock: "true"
spec:
  group: apps.shop-operator.io
  names:
    kind: Wallet
    listKind: WalletList
    plural: wallets
    singular: wallet
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [shopRef, network]
              properties:
                shopRef:
                  type: string
                network:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Network
          type: string
          jsonPath: .spec.network
        - name: Address
          type: string
          jsonPath: .status.address
        - name: Phase
          type: string
          jsonPath: .status.phase
