{{- if .Values.ghcrSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ghcrSecret.name | default "ghcr-secret" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" (.Values.ghcrSecret.registry | default "ghcr.io") .Values.ghcrSecret.username .Values.ghcrSecret.password (printf "%s:%s" .Values.ghcrSecret.username .Values.ghcrSecret.password | b64enc) | b64enc | quote }}
{{- end }}
