apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app        #  shophub-app
  namespace: {{ .Release.Namespace }}  #  shophub
type: Opaque
stringData:
  jwt-secret: {{ required "api.jwtSecret is required" .Values.api.jwtSecret | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-rw:5432/%s"
    .Values.database.username
    .Values.database.password
    .Values.database.clusterName
    .Values.database.name | quote }}
