replicaCount: 1

image:
  repository: ghcr.io/shopp-ops/shop
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: nginx
  host: ""
  tls: []
