name: "My Shop"
availability: standard

database:
  type: standard

apiImage: "ghcr.io/shopp-ops/shophub-api:latest"
webImage: "ghcr.io/shopp-ops/shophub-web:latest"

adminEmail: "admin@shop.local"
host: "shop.example.com"
walletAddress: ""
discordChannelRef: ""
